# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSearchClient, RawSearchClient
from .types.search_get_analytics_summary_response import SearchGetAnalyticsSummaryResponse
from .types.search_get_trace_detail_response import SearchGetTraceDetailResponse
from .types.search_search_request_attribute_filters_item import SearchSearchRequestAttributeFiltersItem
from .types.search_search_request_sort_by import SearchSearchRequestSortBy
from .types.search_search_request_sort_order import SearchSearchRequestSortOrder
from .types.search_search_response import SearchSearchResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchClient
        """
        return self._raw_client

    def search(
        self,
        *,
        start_time: str,
        end_time: str,
        query: typing.Optional[str] = OMIT,
        trace_id: typing.Optional[str] = OMIT,
        span_id: typing.Optional[str] = OMIT,
        model: typing.Optional[typing.Sequence[str]] = OMIT,
        provider: typing.Optional[typing.Sequence[str]] = OMIT,
        function_id: typing.Optional[str] = OMIT,
        function_name: typing.Optional[str] = OMIT,
        has_error: typing.Optional[bool] = OMIT,
        min_tokens: typing.Optional[float] = OMIT,
        max_tokens: typing.Optional[float] = OMIT,
        min_duration: typing.Optional[float] = OMIT,
        max_duration: typing.Optional[float] = OMIT,
        attribute_filters: typing.Optional[typing.Sequence[SearchSearchRequestAttributeFiltersItem]] = OMIT,
        limit: typing.Optional[float] = OMIT,
        offset: typing.Optional[float] = OMIT,
        sort_by: typing.Optional[SearchSearchRequestSortBy] = OMIT,
        sort_order: typing.Optional[SearchSearchRequestSortOrder] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchSearchResponse:
        """
        Parameters
        ----------
        start_time : str

        end_time : str

        query : typing.Optional[str]

        trace_id : typing.Optional[str]

        span_id : typing.Optional[str]

        model : typing.Optional[typing.Sequence[str]]

        provider : typing.Optional[typing.Sequence[str]]

        function_id : typing.Optional[str]

        function_name : typing.Optional[str]

        has_error : typing.Optional[bool]

        min_tokens : typing.Optional[float]

        max_tokens : typing.Optional[float]

        min_duration : typing.Optional[float]

        max_duration : typing.Optional[float]

        attribute_filters : typing.Optional[typing.Sequence[SearchSearchRequestAttributeFiltersItem]]

        limit : typing.Optional[float]

        offset : typing.Optional[float]

        sort_by : typing.Optional[SearchSearchRequestSortBy]

        sort_order : typing.Optional[SearchSearchRequestSortOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchSearchResponse
            Success

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.search.search(
            start_time="startTime",
            end_time="endTime",
        )
        """
        _response = self._raw_client.search(
            start_time=start_time,
            end_time=end_time,
            query=query,
            trace_id=trace_id,
            span_id=span_id,
            model=model,
            provider=provider,
            function_id=function_id,
            function_name=function_name,
            has_error=has_error,
            min_tokens=min_tokens,
            max_tokens=max_tokens,
            min_duration=min_duration,
            max_duration=max_duration,
            attribute_filters=attribute_filters,
            limit=limit,
            offset=offset,
            sort_by=sort_by,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    def gettracedetail(
        self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SearchGetTraceDetailResponse:
        """
        Parameters
        ----------
        trace_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchGetTraceDetailResponse
            Success

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.search.gettracedetail(
            trace_id="traceId",
        )
        """
        _response = self._raw_client.gettracedetail(trace_id, request_options=request_options)
        return _response.data

    def getanalyticssummary(
        self,
        *,
        start_time: str,
        end_time: str,
        function_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchGetAnalyticsSummaryResponse:
        """
        Parameters
        ----------
        start_time : str

        end_time : str

        function_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchGetAnalyticsSummaryResponse
            Success

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.search.getanalyticssummary(
            start_time="startTime",
            end_time="endTime",
        )
        """
        _response = self._raw_client.getanalyticssummary(
            start_time=start_time, end_time=end_time, function_id=function_id, request_options=request_options
        )
        return _response.data


class AsyncSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchClient
        """
        return self._raw_client

    async def search(
        self,
        *,
        start_time: str,
        end_time: str,
        query: typing.Optional[str] = OMIT,
        trace_id: typing.Optional[str] = OMIT,
        span_id: typing.Optional[str] = OMIT,
        model: typing.Optional[typing.Sequence[str]] = OMIT,
        provider: typing.Optional[typing.Sequence[str]] = OMIT,
        function_id: typing.Optional[str] = OMIT,
        function_name: typing.Optional[str] = OMIT,
        has_error: typing.Optional[bool] = OMIT,
        min_tokens: typing.Optional[float] = OMIT,
        max_tokens: typing.Optional[float] = OMIT,
        min_duration: typing.Optional[float] = OMIT,
        max_duration: typing.Optional[float] = OMIT,
        attribute_filters: typing.Optional[typing.Sequence[SearchSearchRequestAttributeFiltersItem]] = OMIT,
        limit: typing.Optional[float] = OMIT,
        offset: typing.Optional[float] = OMIT,
        sort_by: typing.Optional[SearchSearchRequestSortBy] = OMIT,
        sort_order: typing.Optional[SearchSearchRequestSortOrder] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchSearchResponse:
        """
        Parameters
        ----------
        start_time : str

        end_time : str

        query : typing.Optional[str]

        trace_id : typing.Optional[str]

        span_id : typing.Optional[str]

        model : typing.Optional[typing.Sequence[str]]

        provider : typing.Optional[typing.Sequence[str]]

        function_id : typing.Optional[str]

        function_name : typing.Optional[str]

        has_error : typing.Optional[bool]

        min_tokens : typing.Optional[float]

        max_tokens : typing.Optional[float]

        min_duration : typing.Optional[float]

        max_duration : typing.Optional[float]

        attribute_filters : typing.Optional[typing.Sequence[SearchSearchRequestAttributeFiltersItem]]

        limit : typing.Optional[float]

        offset : typing.Optional[float]

        sort_by : typing.Optional[SearchSearchRequestSortBy]

        sort_order : typing.Optional[SearchSearchRequestSortOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchSearchResponse
            Success

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.search.search(
                start_time="startTime",
                end_time="endTime",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            start_time=start_time,
            end_time=end_time,
            query=query,
            trace_id=trace_id,
            span_id=span_id,
            model=model,
            provider=provider,
            function_id=function_id,
            function_name=function_name,
            has_error=has_error,
            min_tokens=min_tokens,
            max_tokens=max_tokens,
            min_duration=min_duration,
            max_duration=max_duration,
            attribute_filters=attribute_filters,
            limit=limit,
            offset=offset,
            sort_by=sort_by,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    async def gettracedetail(
        self, trace_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SearchGetTraceDetailResponse:
        """
        Parameters
        ----------
        trace_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchGetTraceDetailResponse
            Success

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.search.gettracedetail(
                trace_id="traceId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.gettracedetail(trace_id, request_options=request_options)
        return _response.data

    async def getanalyticssummary(
        self,
        *,
        start_time: str,
        end_time: str,
        function_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchGetAnalyticsSummaryResponse:
        """
        Parameters
        ----------
        start_time : str

        end_time : str

        function_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchGetAnalyticsSummaryResponse
            Success

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.search.getanalyticssummary(
                start_time="startTime",
                end_time="endTime",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.getanalyticssummary(
            start_time=start_time, end_time=end_time, function_id=function_id, request_options=request_options
        )
        return _response.data
