# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .search_search_response_spans_item import SearchSearchResponseSpansItem


class SearchSearchResponse(UniversalBaseModel):
    spans: typing.List[SearchSearchResponseSpansItem]
    total: float
    has_more: typing_extensions.Annotated[bool, FieldMetadata(alias="hasMore")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
